let kichemy = document.getElementById("kichemy-btn");
kichemy.addEventListener("click",function(){
    let div = document.getElementById("aspirer-item-description");
    div.innerHTML = '<h5 class="text-center text-danger display-2 fw-bold">Dorcena Kichemy</h5><p class="text-light"> <img src="img/aspirers/kichemy.png" alt="dorcena kichemy" width="30%" class="aspirer-img">Kichemy and I both attended the same primary and secondary school (College Dominique Savio - CODOSA). He is presently attending Berea College, where he is pursuing a dual-degree program. Every student will agree that he has an out-of-this-world entrepreneurial mindset. If there is a need, Kichemy sells it the next day. He even fabricated the necessities at times. His abilities expanded to the point that he won various entrepreneurial competitions, including <strong class="text-danger">ATHENA (2nd), DIAMOND CHALLENGE, and EMO-HAITI (in which I was his teammate).</strong></p><p class="text-light">Previously, I had little interest in this form of competition. However, he exposed me to this world, and I am now prepared to compete in any Entrepreneurial competition. I began with a <strong class="text-danger">Exposcience (finalist)</strong> and my most recent one is a <strong class="text-danger">Hultprize (4th)</strong>. I am grateful to him for introducing me to this world. <a class="text-danger" href="competitions.html">Click here</a> if want to get more knowledge about my last competition experiences.</p><p class="text-light">Furthermore, being an introvert, I had never consented to the concept of publicizing my accomplishments. Because I do not want to brag, the less attention I had on myself, the better I felt. However, Kichemy made me realize that publicizing your accomplishments is not the same as bragging. Instead, you encourage others to do the same and draw influential individuals to you. He was accurate. Since I began sharing my accomplishments, I havve had multiple messages from individuals expressing their appreciation for what I am doing, encouraging me to keep going, and inviting me to join them in a project they are working on.<br> I will not say that I always feel comfortable sharing my achievements but at least I know what I will gain  from it : <strong class="text-danger">Networking.</strong></p><p class="text-light">Thus, if you want to grow your network, you are now aware of what to do. If you have no achievement, go participating in competitions (not necessary entrepreneurial, it can be debate, robotic or any subject you are very fond of) or build your own project. GET OUT OF YOUR BUBBLE.</p>';
})

let mitchello = document.getElementById("mitchello-btn");
mitchello.addEventListener("click",function(){
    let div = document.getElementById("aspirer-item-description");
    div.innerHTML = '<h5 class="text-center text-danger display-2 fw-bold">Vincent Mitchello</h5><p class="text-light"> <img src="img/aspirers/mitchello.png" alt="vincent mitchello" width="30%" class="aspirer-img">Mitchello and I both attended the same primary and secondary school (College Dominique Savio - CODOSA). This man is not afraid of anyone (even the school director). He has also entrepreneurial skills but his skills are more oriented to computer science and mecanical engineering. Every classmate who had a problem with their phone or their laptop, contacted him because he was a reference in this area. Bring any new technology to him and he will show you how to handle it. He is a natural computer scientist. Once, I asked him with his massive skills in the computer field what he will do after school. On the top of all that, when we competed at <strong class="text-danger">EMO-HAITI (1st)</strong>, he was the first one to understand how to handle <strong class="text-danger">the rasberry pi using python</strong> even though we never used one before.</strong></p><p class="text-light">Furthermore, he was my best friend at school. He was ready to support me in any single situation. This is the reason why he competed with me everywhere I went : <strong class="text-danger">FLL (1st), Exposcience, Emo-Haiti(1st) and so on.</strong> I was responsible to bring an idea and he was the one who did the prototype for the competition. His loyalty is out-of-the-world. We are even the co-president of Smartworker Corporation.</p><p class="text-light">He also has outstanding skills in graphic design. No doubt that he is responsible for that in Smartworker Corporation. If today I am passionate of computer science, he has a lot to do in that. He is still an example for me. Thank you for all your support !</p>';
})

let chenko = document.getElementById("chenko-btn");
chenko.addEventListener("click",function(){
    let div = document.getElementById("aspirer-item-description");
    div.innerHTML = '<h5 class="text-center text-danger display-2 fw-bold">Michel Shevchenko</h5><p class="text-light"> <img src="img/aspirers/chenko.png" alt="michel shevchenko" width="30%" class="aspirer-img">Shevchenko and I both attended the same primary and secondary school (College Dominique Savio - CODOSA). He has also strong entrepreneurial skills. His abilities expanded to the point that he won various entrepreneurial competitions, including <strong class="text-danger">ATHENA (2nd), DIAMOND CHALLENGE, Exposcience, and EMO-HAITI (in which I was his teammate).</strong></p><p class="text-light">However, this is not what amazed me the most from him. He is the one that will never give up even if all odds are against him. The one that is ready to take any risk if the result may lead to a bright path. I always tell him that he has to take calculated risk and he answers : <em>"if it is calculated then it is not a risk".</em> Once, he told me that I play too soft in life and I could be further if I take the risks that I was avoiding. He was right.</p><p class="text-light">Even though now I do not take as many risks as I could but I have made progress. Hence, I advice you all to not look at only the bad outputs of a risk. <strong class="text-danger">Instead of asking yourself : "what if it does not work?" ask : "What if it does?"</strong> Most of the time, there is glory on the other side of a risk. If not, there is a lesson. And this, I realized and experienced that because Shevchenko was my friend.</p>';
})

let leyg = document.getElementById("leyg-btn");
leyg.addEventListener("click",function(){
    let div = document.getElementById("aspirer-item-description");
    div.innerHTML = '<h5 class="text-center text-danger display-2 fw-bold">Dorissaint Wikensley</h5><p class="text-light"> <img src="img/aspirers/wikensley.png" alt="wikensley dorissaint" width="25%" class="aspirer-img" style="margin-top: -4%;">Wikensley is presently attending Université Quiskeya, where he is pursuing a industrial engineering degree. Every student will agree that he has an out-of-this-world sense of analysis. He also participated at Hultprize(2nd). I may be exaggerating when I say that knowing him has raised my confidence by 150% and helped me get to know myself better. That is how I felt after meeting him.</p><p class="text-light">He helped me understand that I also had a fantastic sense of analysis, deep thinking, problem-solving and how to better analyse people after some intense conversation with him. He was always able to see the best in me, even skills that I have ignored for so long. This is the primary reason I began providing helpful counsel to my peers. Furthermore, the feedbacks verified his remarks. Many people were thankful for my advise since it helped them overcome significant challenges (whether they were mental, social, or professional in nature).</p><p class="text-light">I am really grateful I met him. If I could spend more time with him, I would because at every conversation I learn something new on myself.</p>';
})